version: '3'
services:
  node:
    image: node:14-alpine
    restart: always
    working_dir: /app
    command: 'yarn production'
    volumes:
      - .:/app
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-data:/data
