version: '3'
services:
  node:
    image: node:14-alpine
    restart: always
    working_dir: /app
    command: 'yarn production'
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - redis
  redis:
    image: redis:alpine
    restart: always
    #command: redis-server
    ports:
      - 6379:6379
    volumes:
      - ./redis-data:/data

