version: '2'
services:
  node:
    image: node:14-alpine
    restart: always
    working_dir: /app
    command: 'yarn production'
    volumes:
      - .:/app
    ports:
      - 3000:3000
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis-conf:/usr/local/etc/redis
      - ./redis-data:/data

